name: Gradle Build

on:
  pull_request:
    branches: ['*']
  push:
    branches: ['*']
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-rc.[1-9][0-9]*'

jobs:
  build:
    uses: rahulsom/_/.github/workflows/gradle.yml@main
    with:
      # Defaults (can be overriden here)
      java-version: 21
      java-distribution: 'zulu'
      publish-candidates: true
    secrets:
      ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.ORG_GRADLE_PROJECT_sonatypeUsername }}
      ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.ORG_GRADLE_PROJECT_sonatypePassword }}
      ORG_GRADLE_PROJECT_signingKey:       ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingPassword:  ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}
